modLoader="javafml"
loaderVersion="[31,)"
#issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="xnetgasses"
version="${file.jarVersion}"
displayName="XNet Gasses"
#logoFile="examplemod.png"
credits="Credits go to bradyaidanc and mcjty for creating mekanism and xnet"
authors="Terrails"
description=''' A simple addon for xnet that enables the movement of gasses from mekanism. '''

[[dependencies.xnetgasses]]
    modId="mekanism"
    mandatory=true
    versionRange="[1.15.2-9,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnetgasses]]
    modId="xnet"
    mandatory=true
    versionRange="[1.15-2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnetgasses]]
    modId="rftoolsbase"
    mandatory=true
    versionRange="[1.15-1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.xnetgasses]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.15-4,)"
    ordering="NONE"
    side="BOTH"