modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Terrails/XNetGases/issues"

[[mods]]
modId="xnetgases"
version="${file.jarVersion}"
displayName="XNet Gases"
logoFile="xnetgases.png"
credits="Credits go to bradyaidanc and mcjty for creating mekanism and xnet"
authors="Terrails"
description=''' A simple addon for xnet that enables the movement of gases from mekanism. '''

[[dependencies.xnetgases]]
    modId="mekanism"
    mandatory=true
    versionRange="[1.18.2-10,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.xnetgases]]
    modId="xnet"
    mandatory=true
    versionRange="[1.18-4,)"
    ordering="AFTER"
    side="BOTH"